#!/usr/bin/env python3
"""Generate the homepage SVG art partials from the maths in home-art.jsx.

The old art components computed their geometry in JSX at render time. Rather
than hand-copying rendered DOM (unreadable) or hand-translating the loops into
Go templates (easy to get subtly wrong), this reproduces the same arithmetic
once and emits static SVG partials.

Only the three components the page actually rendered are generated. HeroArt,
SealMark, GlyphTriplets, GlyphNoPII and GlyphVault were dead code:
hero-banner.jsx overrode window.Hero with a banner that draws its art in CSS,
and ProductGlyph renders an <img>, not the glyph SVGs.

Re-run after editing, and diff the output against the original render.
"""
import pathlib

A = dict(ink="#2A3340", mineral="#0F3D56", m50="#879EAB", cloud="#F0F2F5",
         slate="#6B7280", white="#FFFFFF")
OUT = pathlib.Path("layouts/partials/home/art")


def num(v):
    """Match JS number formatting: 12 not 12.0, and no trailing zeros."""
    if isinstance(v, int) or v == int(v):
        return str(int(v))
    return repr(round(v, 6)).rstrip("0").rstrip(".")


def iso_pts(cx, cy, w, h):
    return f"{num(cx)},{num(cy-h)} {num(cx+w)},{num(cy)} {num(cx)},{num(cy+h)} {num(cx-w)},{num(cy)}"


def tick(x, y, s=5, c="#C8CCD3", o=0.9):
    return (f'<g stroke="{c}" stroke-width="1" opacity="{num(o)}">'
            f'<line x1="{num(x-s)}" y1="{num(y)}" x2="{num(x+s)}" y2="{num(y)}"/>'
            f'<line x1="{num(x)}" y1="{num(y-s)}" x2="{num(x)}" y2="{num(y+s)}"/></g>')


def stack_diagram():
    cx, w, h, d = 232, 152, 53, 20
    cys = [88, 196, 304]
    fcy, fw, fh, fd = 426, 202, 66, 24
    p = ['{{- /* StackDiagram, generated by scripts/gen_home_art.py */ -}}',
         '<svg class="{{ .class }}" viewBox="0 0 470 548" fill="none" xmlns="http://www.w3.org/2000/svg"',
         '     role="img" aria-label="Three trust layers resting on one certified foundation">',
         '  <defs>',
         '    <linearGradient id="glsTop" x1="0" y1="0" x2="0.5" y2="1"><stop offset="0" stop-color="#FFFFFF" stop-opacity="0.9"/><stop offset="1" stop-color="#DCE3EB" stop-opacity="0.48"/></linearGradient>',
         '    <linearGradient id="glsSide" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#CBD3DC" stop-opacity="0.55"/><stop offset="1" stop-color="#AEBAC6" stop-opacity="0.4"/></linearGradient>',
         '    <linearGradient id="datTop" x1="0" y1="0" x2="0.5" y2="1"><stop offset="0" stop-color="#235F80" stop-opacity="0.95"/><stop offset="1" stop-color="#0E3247" stop-opacity="0.97"/></linearGradient>',
         '    <linearGradient id="datSide" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#0E3247" stop-opacity="0.94"/><stop offset="1" stop-color="#0A2738" stop-opacity="0.97"/></linearGradient>',
         '    <linearGradient id="sgFound" x1="0" y1="0" x2="0.6" y2="1"><stop offset="0" stop-color="#EEF1F5" stop-opacity="0.92"/><stop offset="1" stop-color="#D8DEE5" stop-opacity="0.68"/></linearGradient>',
         '    <radialGradient id="sgShadow" cx="0.5" cy="0.5" r="0.5"><stop offset="0" stop-color="#2A3340" stop-opacity="0.14"/><stop offset="1" stop-color="#2A3340" stop-opacity="0"/></radialGradient>',
         '    <filter id="glsShadow" x="-40%" y="-40%" width="180%" height="220%"><feDropShadow dx="0" dy="9" stdDeviation="9" flood-color="#2A3340" flood-opacity="0.13"/></filter>',
         '  </defs>']
    for x, y in ((40, 62), (430, 62), (40, 508), (430, 508)):
        p.append("  " + tick(x, y))
    p.append(f'  <ellipse cx="{num(cx)}" cy="{num(fcy+fh+32)}" rx="{num(fw*0.92)}" ry="20" fill="url(#sgShadow)"/>')
    p += ['  <g opacity="0.55">',
          f'    <line x1="58" y1="74" x2="58" y2="356" stroke="{A["mineral"]}" stroke-width="1.4" stroke-dasharray="5 6"/>',
          f'    <path d="M54,352 L58,360 L62,352" stroke="{A["mineral"]}" stroke-width="1.4"/>',
          f'    <text x="44" y="216" transform="rotate(-90 44 216)" text-anchor="middle" font-size="10.5" fill="{A["slate"]}" font-family="Geist, sans-serif" letter-spacing="0.08em">REQUEST &#183; INPUT</text>',
          '  </g>']
    for i, cy in enumerate(cys):
        data = i == 2
        left = f"{num(cx-w)},{num(cy)} {num(cx)},{num(cy+h)} {num(cx)},{num(cy+h+d)} {num(cx-w)},{num(cy+d)}"
        right = f"{num(cx)},{num(cy+h)} {num(cx+w)},{num(cy)} {num(cx+w)},{num(cy+d)} {num(cx)},{num(cy+h+d)}"
        p.append(f'  <g class="hp-isoL" data-depth="{i-1}" filter="url(#glsShadow)">')
        p.append(f'    <polygon points="{left}" fill="url(#{"datSide" if data else "glsSide"})"/>')
        p.append(f'    <polygon points="{right}" fill="url(#{"datSide" if data else "glsSide"})"/>')
        p.append(f'    <polygon points="{right}" fill="#2A3340" fill-opacity="0.12"/>')
        p.append(f'    <polygon points="{iso_pts(cx, cy, w, h)}" fill="url(#{"datTop" if data else "glsTop"})" '
                 f'stroke="{"rgba(255,255,255,0.34)" if data else "rgba(99,118,138,0.34)"}" stroke-width="1.1"/>')
        p.append(f'    <polygon points="{num(cx)},{num(cy-h)} {num(cx-w)},{num(cy)} {num(cx)},{num(cy)}" '
                 f'fill="#FFFFFF" fill-opacity="{0.1 if data else 0.34}"/>')
        p.append(f'    <circle cx="{num(cx)}" cy="{num(cy)}" r="14" fill="{"rgba(255,255,255,0.16)" if data else "#FFFFFF"}" '
                 f'stroke="{"rgba(255,255,255,0.6)" if data else "rgba(99,118,138,0.5)"}" stroke-width="1.1"/>')
        p.append(f'    <text x="{num(cx)}" y="{num(cy+4)}" text-anchor="middle" font-size="12.5" font-weight="700" '
                 f'fill="{"#FFFFFF" if data else A["mineral"]}" font-family="Geist, sans-serif">0{i+1}</text>')
        p.append('  </g>')
    p.append('  <g filter="url(#glsShadow)">')
    p.append(f'    <polygon points="{num(cx-fw)},{num(fcy)} {num(cx)},{num(fcy+fh)} {num(cx)},{num(fcy+fh+fd)} {num(cx-fw)},{num(fcy+fd)}" fill="url(#glsSide)"/>')
    p.append(f'    <polygon points="{num(cx)},{num(fcy+fh)} {num(cx+fw)},{num(fcy)} {num(cx+fw)},{num(fcy+fd)} {num(cx)},{num(fcy+fh+fd)}" fill="#2A3340" fill-opacity="0.1"/>')
    p.append(f'    <polygon points="{iso_pts(cx, fcy, fw, fh)}" fill="url(#sgFound)" stroke="rgba(99,118,138,0.34)" stroke-width="1.1"/>')
    p.append(f'    <text x="{num(cx)}" y="{num(fcy+5)}" text-anchor="middle" font-size="12.5" fill="{A["slate"]}" font-family="Geist, sans-serif" letter-spacing="0.06em">ONE FOUNDATION</text>')
    p.append('  </g>')
    p.append('</svg>')
    return "\n".join(p) + "\n"


def resource_art():
    cx = 200
    cys = [42, 88, 134]
    tints = ["url(#rgTop)", "url(#rgMid)", "url(#rgBot)"]
    p = ['{{- /* ResourceArt, generated by scripts/gen_home_art.py */ -}}',
         '<svg class="{{ .class }}" style="{{ .style | safeCSS }}" viewBox="0 0 400 200" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">',
         '  <defs>',
         '    <linearGradient id="rgTop" x1="0" y1="0" x2="0.6" y2="1"><stop offset="0" stop-color="#F3F5F8"/><stop offset="1" stop-color="#DCE2E8"/></linearGradient>',
         '    <linearGradient id="rgMid" x1="0" y1="0" x2="0.6" y2="1"><stop offset="0" stop-color="#A7BBC8"/><stop offset="1" stop-color="#7E96A7"/></linearGradient>',
         '    <linearGradient id="rgBot" x1="0" y1="0" x2="0.5" y2="1"><stop offset="0" stop-color="#1E5676"/><stop offset="1" stop-color="#0E3247"/></linearGradient>',
         '  </defs>']
    for i, cy in enumerate(cys):
        p.append('  <g>')
        p.append(f'    <polygon points="{num(cx-112)},{num(cy)} {num(cx)},{num(cy+39)} {num(cx)},{num(cy+51)} {num(cx-112)},{num(cy+12)}" fill="{"#0A2C40" if i == 2 else "#C4CDD6"}"/>')
        p.append(f'    <polygon points="{num(cx)},{num(cy+39)} {num(cx+112)},{num(cy)} {num(cx+112)},{num(cy+12)} {num(cx)},{num(cy+51)}" fill="{A["ink"]}" fill-opacity="0.18"/>')
        p.append(f'    <polygon points="{iso_pts(cx, cy, 112, 39)}" fill="{tints[i]}" stroke="{A["mineral"] if i == 2 else "#A7B2BD"}" stroke-width="1" stroke-opacity="0.8"/>')
        p.append('  </g>')
    p.append('</svg>')
    return "\n".join(p) + "\n"


def closing_art():
    vp = [935, 140]
    o = dict(x=96, y=20, w=1010, h=420)
    N = 6
    p = ['{{- /* ClosingArt, generated by scripts/gen_home_art.py */ -}}',
         '<svg class="{{ .class }}" viewBox="0 0 1240 460" fill="none" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">']
    for i in range(N):
        t = i / (N - 1)
        k = t * 0.86
        x = o["x"] + (vp[0] - o["x"]) * k
        y = o["y"] + (vp[1] - o["y"]) * k
        w = o["w"] * (1 - k)
        h = o["h"] * (1 - k)
        fo = 0.06 if i == N - 1 else 0.012 + t * 0.014
        so = 0.05 + t * 0.08
        p.append(f'  <rect x="{num(x)}" y="{num(y)}" width="{num(w)}" height="{num(h)}" rx="12" '
                 f'fill="{A["white"]}" fill-opacity="{num(fo)}" stroke="{A["white"]}" stroke-width="1" stroke-opacity="{num(so)}"/>')
    p.append('</svg>')
    return "\n".join(p) + "\n"


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    for name, fn in (("stack-diagram", stack_diagram),
                     ("resource-art", resource_art),
                     ("closing-art", closing_art)):
        f = OUT / f"{name}.html"
        f.write_text(fn())
        print(f"  {f}  {f.stat().st_size} bytes")
